import fs from 'node:fs'
import path from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { loadConfig } from '../src/core/config.js'
import { resolveBinaries, run } from '../src/core/media/ffmpeg.js'
import { probe } from '../src/core/media/probe.js'
import { detectSilences, measureLoudness } from '../src/core/media/measure.js'
import { decodePcm16k } from '../src/core/media/decode.js'
import { detectSceneCuts, sampleThumbnails, contactSheet, extractFrame } from '../src/core/vision/frames.js'
import { dhash, dedupByHash } from '../src/core/vision/dhash.js'
import { resolveSource, assertKindSupports } from '../src/core/source/resolve.js'
import { detectSpeech } from '../src/core/audio/vad.js'

/**
 * Integration tests against media generated by ffmpeg itself (lavfi), so the repo ships no binary fixtures.
 * The clip: 8 s, 640×360, two distinct scenes (blue then red at t=4), a 440 Hz tone for 3 s then 2 s silence then tone.
 */
const dir = path.resolve('.ollos-test-media')
const clip = path.join(dir, 'clip.mp4')
const config = loadConfig({ home: path.join(dir, 'home') })

beforeAll(async () => {
  fs.mkdirSync(dir, { recursive: true })
  const { ffmpeg } = resolveBinaries(config)
  await run(ffmpeg, [
    '-y', '-v', 'error',
    '-f', 'lavfi', '-i', 'color=c=blue:s=640x360:d=4,format=yuv420p',
    '-f', 'lavfi', '-i', 'color=c=red:s=640x360:d=4,format=yuv420p',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=3',
    '-f', 'lavfi', '-i', 'anullsrc=r=44100:cl=mono:d=2',
    '-f', 'lavfi', '-i', 'sine=frequency=660:duration=3',
    '-filter_complex', '[0:v][1:v]concat=n=2:v=1:a=0[v];[2:a][3:a][4:a]concat=n=3:v=0:a=1[a]',
    '-map', '[v]', '-map', '[a]', '-c:v', 'libx264', '-preset', 'ultrafast', '-c:a', 'aac', '-shortest', clip,
  ])
})
afterAll(() => fs.rmSync(dir, { recursive: true, force: true }))

describe('media layer on a generated clip', () => {
  it('probes kind, duration, aspect and streams', async () => {
    const info = await probe(clip, config)
    expect(info.kind).toBe('video')
    expect(info.durationSec).toBeGreaterThan(7)
    expect(info.video).toMatchObject({ width: 640, height: 360 })
    expect(info.aspect?.ratio).toBe('16:9')
    expect(info.audio?.channels).toBe(1)
  })

  it('resolves a local path and rejects unsupported tasks early', async () => {
    const src = await resolveSource(clip, config)
    expect(src.origin).toBe('local')
    expect(() => assertKindSupports({ ...src.info, audio: undefined }, 'transcribe')).toThrow(/audio stream/)
    await expect(resolveSource(path.join(dir, 'missing.mp4'), config)).rejects.toMatchObject({ code: 'SOURCE_NOT_FOUND' })
  })

  it('decodes to 16 kHz mono float32', async () => {
    const pcm = await decodePcm16k(clip, config, { fromSec: 0, toSec: 2 })
    expect(pcm.length).toBeGreaterThan(16000 * 1.9)
    expect(pcm.length).toBeLessThan(16000 * 2.1)
  })

  it('finds the 2 s silence gap', async () => {
    const s = await detectSilences(clip, config, { noiseDb: -35, minDurationSec: 1 })
    expect(s.length).toBe(1)
    expect(s[0]!.startSec).toBeGreaterThan(2.5)
    expect(s[0]!.durationSec).toBeGreaterThan(1.5)
  })

  it('measures loudness', async () => {
    const l = await measureLoudness(clip, config)
    expect(l.integratedLufs).toBeLessThan(0)
    expect(l.integratedLufs).toBeGreaterThan(-70)
    expect(Number.isFinite(l.truePeakDbtp)).toBe(true)
  })

  it('detects the hard cut at ~4 s and dedups the two scenes by hash', async () => {
    const cuts = await detectSceneCuts(clip, config, { threshold: 0.3 })
    expect(cuts.length).toBe(1)
    expect(cuts[0]).toBeGreaterThan(3.5)
    expect(cuts[0]).toBeLessThan(4.5)
    const { thumbs, pts } = await sampleThumbnails(clip, config, { fps: 1 })
    expect(thumbs.length).toBeGreaterThanOrEqual(7)
    const kept = dedupByHash(thumbs.map((t, i) => ({ index: i, pts: pts[i]!, hash: dhash(t) })), 6)
    // flat colour frames hash identically; only frame 0 survives (blue→red flat frames both hash to zero bits)
    expect(kept.length).toBeGreaterThanOrEqual(1)
    expect(kept.length).toBeLessThanOrEqual(2)
  })

  it('reports cut timestamps in source time even when a window is set (issue #1)', async () => {
    // -ss sits before -i, so ffmpeg's own pts_time is relative to the seek; a window starting at 2 s must
    // still report the cut at ~4 s of the source, not ~2 s into the window.
    const cuts = await detectSceneCuts(clip, config, { threshold: 0.3, fromSec: 2, toSec: 8 })
    expect(cuts.length).toBe(1)
    expect(cuts[0]).toBeGreaterThan(3.5)
    expect(cuts[0]).toBeLessThan(4.5)
  })

  it('extracts a frame and builds a contact sheet', async () => {
    const a = await extractFrame(clip, 1, config, { width: 320 })
    const b = await extractFrame(clip, 6, config, { width: 320 })
    expect(a.length).toBeGreaterThan(500)
    const sheet = await contactSheet([{ jpeg: a, pts: 1, index: 1 }, { jpeg: b, pts: 6, index: 2 }], { cols: 2, tileWidth: 240 })
    expect(sheet.subarray(0, 2)).toEqual(Buffer.from([0xff, 0xd8]))
  })

  it('VAD returns a result with either engine and covers the tone regions', async () => {
    const pcm = await decodePcm16k(clip, config)
    const v = await detectSpeech(pcm, config)
    expect(['silero', 'energy']).toContain(v.engine)
    expect(v.totalSec).toBeGreaterThan(7)
    expect(v.speechSec).toBeLessThanOrEqual(v.totalSec)
  })
})
